### ISSUE TITLE
Scheduler-Call not ending correctly

### ISSUE THREAD

**Issue by manuelLink** [Gernott/wp_directmailreturn#4]
The call from the TYPO3-Scheduler does not exit correctly if there are no E-Mails.
This Results in the Job still being marked as running in the Backend.

the issue is line 130 in Classes/Command/AnalyzeMailCommand.php

using "return true;" instead of "die('');" seems to resolve the issue.

**Comment by Gernott** [comment]
Thank you for reporting.
Would you fix this, test it and make a pull request?

**Comment by manuelLink** [comment]
#5 created a pull request
